### ISSUE TITLE
Larynx voices sometimes erroring

### ISSUE THREAD

**Issue by aleclol** [synesthesiam/opentts#8] opened 2021-04-23 03:22 UTC
Hello, today I was trying to use one of the new larynx voices and got this traceback.

```
Traceback (most recent call last):
  File "/app/usr/local/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/app/usr/local/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/app/app.py", line 371, in app_say
    use_cache=use_cache,
  File "/app/app.py", line 244, in text_to_wav
    line, voice_id, vocoder=vocoder, denoiser_strength=denoiser_strength
  File "/app/tts.py", line 1377, in say
    for _, audio in text_and_audios:
  File "/app/usr/local/lib/python3.7/site-packages/larynx/__init__.py", line 82, in text_to_speech
    sentence.tokens, word_indexes=word_indexes, word_breaks=True
  File "/app/usr/local/lib/python3.7/site-packages/gruut/phonemize.py", line 207, in phonemize
    for word, word_phonemes in self.predict(words=words_to_guess):
  File "/app/usr/local/lib/python3.7/site-packages/gruut/phonemize.py", line 247, in predict
    words, model_path=self.g2p_model_path, **kwargs
  File "/app/usr/local/lib/python3.7/site-packages/phonetisaurus/__init__.py", line 60, in predict
    phonetisaurus_cmd, env=env, universal_newlines=True
  File "/app/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/app/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['phonetisaurus-apply', '--model', '/app/usr/local/lib/python3.7/site-packages/gruut/data/en-us/g2p.fst', '--word_list', '/tmp/tmpyuws4fry.txt', '--nbest', '1']' returned non-zero exit status 127.
Exception ignored in: <function Wave_write.__del__ at 0x7f81e4ad1e60>
Traceback (most recent call last):
  File "/app/usr/local/lib/python3.7/wave.py", line 327, in __del__
    self.close()
  File "/app/usr/local/lib/python3.7/wave.py", line 445, in close
    self._ensure_header_written(0)
  File "/app/usr/local/lib/python3.7/wave.py", line 463, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
```

BTW: Thank you so much for making this! It is amazing to have so many voices easily accessible.

**Comment by synesthesiam** [comment] 2021-04-27 20:37
You're welcome! Thank you for the bug report; I've figured out what the problem is.

When Rhasspy has to guess a word's pronunciation, it calls `phonetisaurus-apply`. This requires Python to be in the `PATH`, but it isn't because I'm doing something unusual (compiling from source).

Adding near the end of the `Dockerfile` fixes it:

```
ENV PATH=/app/usr/local/bin:${PATH}
```

I'll be pushing an updated set of Docker images soon with the fix :+1:

**Comment by synesthesiam** [comment] 2021-04-29 15:17
Should be fixed now. Please re-open if there are problems.

**Closed by synesthesiam** 2021-04-29 15:17 UTC
Labels: bug
